export const apiErrorCodes = {
  SOMETHING_WENT_WRONG: 0,
  SERVER_OVERLOADED: 1,
  RESOURCE_NOT_FOUND: 2,
  ITEM_DOES_NOT_EXIST: 3,
  VALIDATION_ERROR: 4,
  INVAlID_VALUE: 5,
  INCORRECT_FORMAT: 6,
  EXPIRED_VALUE: 7,
  INVALID_CREDENTIALS: 8,
  ACCOUNT_VERIFICATION_REQUIRED: 9,
  ACCOUNT_DISABLED: 10,
  ACCOUNT_LOCKED: 11,
  ACCOUNT_EXPIRED: 12,
  ACCOUNT_CREDENTIALS_EXPIRED: 13,
  RESOURCE_ACCESS_NOT_ALLOWED: 14,
  ACCOUNT_NOT_FOUND: 15,
  USER_WITH_EMAIL_ALREADY_EXISTS: 20
} as const;
export const apiErrorMessages = {
  0: 'Something went wrong',
  1: 'The server is up, but overloaded with requests. Try again later',
  2: 'Requested resource was not found',
  3: 'The item does not exist',
  4: 'Validation errors in your request',
  5: 'Oops! The value is invalid',
  6: 'Oops! The format is not correct',
  7: 'Oops! The value has expired',
  8: 'Authentication credentials were missing or incorrect',
  9: 'User account verification is required',
  10: 'User account is disabled',
  11: 'User account is locked',
  12: 'User account expired',
  13: 'User account credentials expired',
  14: 'You are not allowed to access this resource',
  15: 'User account not found',
  20: 'User with email already exists'
} as const;
