const AUTHENTICATION_ROUTE = 'authentication';
const TRANSACT_ROUTE = 'transact';
const TRADE_ROUTE = 'trade';
const ADMINISTRATION_ROUTE = 'administration';
const ADMIN_USERS_ROUTE = `${ADMINISTRATION_ROUTE}/users`;
const ADMIN_CURRENCIES_ROUTE = `${ADMINISTRATION_ROUTE}/currencies`;

export enum WebRoute {
  ROOT = '',
  DASHBOARD = 'dashboard',
  AUTHENTICATION = AUTHENTICATION_ROUTE,
  LOGIN = `${AUTHENTICATION_ROUTE}/login`,
  REGISTER = `${AUTHENTICATION_ROUTE}/register`,
  VERIFY_ACCOUNT = `${AUTHENTICATION_ROUTE}/verify`,
  RESET_PASSWORD = `${AUTHENTICATION_ROUTE}/reset-password`,
  WALLETS = 'wallets',
  TRANSACT = TRANSACT_ROUTE,
  MANAGE_TRANSACTIONS = `${TRANSACT_ROUTE}/manage-transactions`,
  TRADE = TRADE_ROUTE,
  MANAGE_TRADES = `${TRADE_ROUTE}/manage-trades`,
  PROFILE = 'profile',
  ADMINISTRATION = ADMINISTRATION_ROUTE,
  MANAGE_USERS = ADMIN_USERS_ROUTE,
  NEW_USER = `${ADMIN_USERS_ROUTE}/new-user`,
  MANAGE_CURRENCIES = `${ADMIN_CURRENCIES_ROUTE}`,
  NEW_CURRENCY = `${ADMIN_CURRENCIES_ROUTE}/new-currency`,
}
