export const apiErrorCodes = {
  SOMETHING_WENT_WRONG: 0,
  SERVER_OVERLOADED: 1,
  RESOURCE_NOT_FOUND: 2,
  ITEM_DOES_NOT_EXIST: 3,
  VALIDATION_ERROR: 4,
  INVAlID_VALUE: 5,
  INCORRECT_FORMAT: 6,
  EXPIRED_VALUE: 7,
  INVALID_CREDENTIALS: 8,
  ACCOUNT_VERIFICATION_REQUIRED: 9,
  ACCOUNT_DISABLED: 10,
  ACCOUNT_LOCKED: 11,
  ACCOUNT_EXPIRED: 12,
  ACCOUNT_CREDENTIALS_EXPIRED: 13,
  RESOURCE_ACCESS_NOT_ALLOWED: 14,
  ACCOUNT_NOT_FOUND: 15,
  USER_WITH_EMAIL_ALREADY_EXISTS: 20,
} as const;

export const apiErrorMessages = {
  [apiErrorCodes.SOMETHING_WENT_WRONG]: 'Something went wrong',
  [apiErrorCodes.SERVER_OVERLOADED]:
    'The server is up, but overloaded with requests. Try again later',
  [apiErrorCodes.RESOURCE_NOT_FOUND]: 'Requested resource was not found',
  [apiErrorCodes.ITEM_DOES_NOT_EXIST]: 'The item does not exist',
  [apiErrorCodes.VALIDATION_ERROR]: 'Validation errors in your request',
  [apiErrorCodes.INVAlID_VALUE]: 'Oops! The value is invalid',
  [apiErrorCodes.INCORRECT_FORMAT]: 'Oops! The format is not correct',
  [apiErrorCodes.EXPIRED_VALUE]: 'Oops! The value has expired',
  [apiErrorCodes.INVALID_CREDENTIALS]: 'Authentication credentials were missing or incorrect',
  [apiErrorCodes.ACCOUNT_VERIFICATION_REQUIRED]: 'User account verification is required',
  [apiErrorCodes.ACCOUNT_DISABLED]: 'User account is disabled',
  [apiErrorCodes.ACCOUNT_LOCKED]: 'User account is locked',
  [apiErrorCodes.ACCOUNT_EXPIRED]: 'User account expired',
  [apiErrorCodes.ACCOUNT_CREDENTIALS_EXPIRED]: 'User account credentials expired',
  [apiErrorCodes.RESOURCE_ACCESS_NOT_ALLOWED]: 'You are not allowed to access this resource',
  [apiErrorCodes.ACCOUNT_NOT_FOUND]: 'User account not found',
  [apiErrorCodes.USER_WITH_EMAIL_ALREADY_EXISTS]: 'User with email already exists',
} as const;
