import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  TuiButtonModule,
  TuiExpandModule,
  TuiGroupModule,
  TuiHintModule,
  TuiHostedDropdownModule,
  TuiLabelModule,
  TuiLinkModule,
  TuiLoaderModule,
  TuiModeModule,
  TuiNotificationModule,
  TuiScrollbarModule,
  TuiSvgModule,
  TuiTextfieldControllerModule,
} from '@taiga-ui/core';
import {
  TuiActiveZoneModule,
  TuiAutoFocusModule,
  TuiHoveredModule,
  TuiLetModule,
} from '@taiga-ui/cdk';
import {
  TuiAvatarModule,
  TuiInputCountModule,
  TuiInputModule,
  TuiIslandModule,
  TuiMarkerIconModule,
  TuiStepperModule,
  TuiTabsModule,
  TuiTagModule,
} from '@taiga-ui/kit';
import { TuiBlockStatusModule } from '@taiga-ui/layout';
import { TuiReorderModule, TuiTableModule, TuiTablePaginationModule } from '@taiga-ui/addon-table';
import { TuiAppBarModule, TuiSidebarModule } from '@taiga-ui/addon-mobile';
import {
  TuiAxesModule,
  TuiLegendItemModule,
  TuiLineChartModule,
  TuiRingChartModule,
} from '@taiga-ui/addon-charts';
import { TuiMoneyModule } from '@taiga-ui/addon-commerce';
import {
  AvatarComponent,
  BlockStatusComponent,
  ButtonComponent,
  CardComponent,
  ChartLegendItemComponent,
  ExpandComponent,
  GroupComponent,
  HeaderComponent,
  IconButtonComponent,
  IconComponent,
  LineChartComponent,
  LinkComponent,
  LoadingIndicatorComponent,
  LogoComponent,
  MenuComponent,
  MenuFooterComponent,
  MenuHeaderComponent,
  MoneyComponent,
  NotificationComponent,
  RingChartComponent,
  SearchFieldComponent,
  SideMenuComponent,
  StepperComponent,
  TableComponent,
  TabsComponent,
  TagComponent,
} from './components';

@NgModule({
  declarations: [
    ButtonComponent,
    HeaderComponent,
    CardComponent,
    LoadingIndicatorComponent,
    LogoComponent,
    LinkComponent,
    IconComponent,
    StepperComponent,
    NotificationComponent,
    MenuComponent,
    MenuHeaderComponent,
    SideMenuComponent,
    MenuFooterComponent,
    MoneyComponent,
    LineChartComponent,
    RingChartComponent,
    ChartLegendItemComponent,
    TableComponent,
    TabsComponent,
    AvatarComponent,
    TagComponent,
    GroupComponent,
    BlockStatusComponent,
    ExpandComponent,
    SearchFieldComponent,
    IconButtonComponent,
  ],
  imports: [
    CommonModule,
    RouterModule,
    TuiSvgModule,
    TuiIslandModule,
    TuiButtonModule,
    TuiLinkModule,
    TuiModeModule,
    TuiLoaderModule,
    TuiStepperModule,
    TuiScrollbarModule,
    TuiNotificationModule,
    TuiAppBarModule,
    TuiLabelModule,
    TuiAvatarModule,
    TuiSidebarModule,
    TuiActiveZoneModule,
    TuiAutoFocusModule,
    TuiMarkerIconModule,
    TuiHintModule,
    TuiLineChartModule,
    TuiAxesModule,
    TuiRingChartModule,
    TuiLegendItemModule,
    TuiMoneyModule,
    TuiHoveredModule,
    TuiTableModule,
    TuiTablePaginationModule,
    TuiTextfieldControllerModule,
    TuiInputModule,
    TuiInputCountModule,
    TuiHostedDropdownModule,
    TuiReorderModule,
    FormsModule,
    ReactiveFormsModule,
    TuiLetModule,
    TuiTabsModule,
    TuiTagModule,
    TuiGroupModule,
    TuiBlockStatusModule,
    TuiExpandModule,
  ],
  exports: [
    ButtonComponent,
    CardComponent,
    HeaderComponent,
    LogoComponent,
    IconComponent,
    LinkComponent,
    LoadingIndicatorComponent,
    StepperComponent,
    NotificationComponent,
    MenuComponent,
    MenuHeaderComponent,
    SideMenuComponent,
    MenuFooterComponent,
    MoneyComponent,
    LineChartComponent,
    RingChartComponent,
    TableComponent,
    TabsComponent,
    AvatarComponent,
    TagComponent,
    GroupComponent,
    BlockStatusComponent,
    ExpandComponent,
    SearchFieldComponent,
    IconButtonComponent,
  ],
})
export class UiComponentsModule {}
