export const webRoutesConfig = {
  root: '',
  dashboard: 'dashboard',
  authentication: 'authentication',
  login: 'authentication/login',
  register: 'authentication/register',
  verifyAccount: 'authentication/verify',
  resetPassword: 'authentication/reset-password',
  wallets: 'wallets',
  transact: 'transact',
  manageTransactions: 'transact/manage-transactions',
  trade: 'trade',
  manageTrades: 'trade/manage-trades',
  profile: 'profile',
  administration: 'administration',
  manageUsers: 'administration/users',
  newUser: 'administration/users/new-user',
  manageCurrencies: 'administration/currencies',
  newCurrency: 'administration/currencies/new-currency',
} as const;
